### PR TITLE
Switch to AWS JS-SDK v3

### PR DESCRIPTION
**Pull request by princed**
Makes a switch to modular AWS which allows to bundle order of magnitude less code.
Also had to update a few dev dependencies along the way to be able deal with the new SDK types.

### CODE REVIEW

**Comment by princed** [comment]
@mpyw Would you be ever interested in merging this? Should I keep the PR open?

**Comment by mpyw** [comment]
@princed Sorry I'm late. I'll bump the major version

**Comment by princed** [comment]
Thank you! Please **don't merge it as is**, I think it needs a couple more of changes:
* Something similar to https://github.com/healthmatch/cloudwatch-front-logger/commit/8012b41395ac6f053e62e0750d1b7688d8e1692b or maybe some more modern babel configuration
* Add `"sideEffects": true` to `package.json` to make it tree-shakeable

**Comment by mpyw** [comment]
Oh, sorry. We should re-release it as `v1.0.1` after some fixes.

> Something similar to https://github.com/healthmatch/cloudwatch-front-logger/commit/8012b41395ac6f053e62e0750d1b7688d8e1692b or maybe some more modern babel configuration

I agree with **modern babel configuration** one that excludes Regenerator Runtime. It will be better if we note supported browsers on README.

> Add `"sideEffects": true` to `package.json` to make it tree-shakeable

Nice, we'll go ahead

**Comment by princed** [comment]
> I agree with modern babel configuration one that excludes Regenerator Runtime

If I remember correctly I only had to add regenerator runtime because existing babel configuration would still generate calls to `regenerator`, but would never import it. If you could set up babel properly without regenerator it'd be awesome, I haven't touched babel for years now 😅

**Pull request merged**
